# Generated by Django 4.2.5 on 2023-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('lost', 'Lost'), ('new', 'New'), ('won', 'Won')], default='new', max_length=10),
        ),
    ]
