# Generated by Django 4.2.5 on 2023-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_team_alter_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('new', 'New'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=10),
        ),
    ]
