# Generated by Django 4.2.8 on 2023-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_lead_priority_alter_lead_status_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('won', 'Won'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('new', 'New')], default='new', max_length=10),
        ),
    ]
