# Generated by Django 4.2.8 on 2024-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('lost', 'Lost'), ('won', 'Won'), ('new', 'New')], default='new', max_length=10),
        ),
    ]
