# Generated by Django 4.2.8 on 2024-01-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_alter_lead_priority_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('won', 'Won'), ('new', 'New'), ('lost', 'Lost')], default='new', max_length=10),
        ),
    ]
