# Generated by Django 4.2.8 on 2024-01-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('contacted', 'Contacted'), ('won', 'Won'), ('new', 'New')], default='new', max_length=10),
        ),
    ]
