# Generated by Django 4.2.8 on 2024-01-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_plan'),
        ('userprofile', '0003_remove_userprofile_active_tead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofiles', to='team.team'),
        ),
    ]
